# Generated by Django 2.1.4 on 2018-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181205_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bpg',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='gp',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='photo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='ppg',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='rpg',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='spg',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
