# Generated by Django 2.1.4 on 2018-12-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181206_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fgpercentage',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='ftpercentage',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
