# Generated by Django 2.1.4 on 2018-12-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181206_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='games',
        ),
    ]
