# Generated by Django 2.1.4 on 2018-12-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_card_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='firstname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='lastname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
