# Generated by Django 2.1.4 on 2018-12-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_card_teamcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='jersey',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
