teamcolors = {'Dallas Mavericks': 'royalblue',
              'Atlanta Hawks': '#E03A3E', 'Boston Celtics': '#007A33',
              'Charlotte Hornets': 'teal', 'Chicago Bulls': '#CE1141',
              'Cleveland Cavaliers': '#FFB81C', 'Denver Nuggets': 'midnightblue',
              'Detroit Pistons': '#006BB6', 'Golden State Warriors': '#FDB927',
              'Houston Rockets': 'red', 'Indiana Pacers': '#002D62',
              'Los Angeles Clippers': '#C8102E', 'Los Angeles Lakers': '#552583',
              'Miami Heat': '#98002E', 'Milwaukee Bucks': '#00471B',
              'Minnesota Timberwolves': '#78BE20', 'Brooklyn Nets': 'black',
              'New York Knicks': '#F58426', 'Orlando Magic': '#0077C0',
              'Philadelphia 76ers': '#ED174C', 'Phoenix Suns': 'purple',
              'Toronto Raptors': '#CE1141', 'Memphis Grizzlies': 'blue',
              'Portland Blazers': '#E03A3E', 'Sacramento Kings': '#5A2D81',
              'San Antonio Spurs': 'fuchsia', 'Oklahoma City Thunder': '#007AC1',
              'Utah Jazz': 'navy', 'Washington Wizards': '#E31837'}
